workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - firebase_credentials
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - "."
        excludes:
          - "ios/"
          - "linux/"
          - "macos/"
          - "web/"
          - "windows/"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      firebase:
        firebase_service_account: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        android:
          app_id: 1:570942649027:android:044b20f2dfe0b64397a876
          groups:
            - android_testers
          artifact_type: "apk"
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.gtn.flutterTestApp
      groups:
        - firebase_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - "."
        excludes:
          - "android/"
          - "linux/"
          - "macos/"
          - "web/"
          - "windows/"
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      firebase:
        firebase_service_account: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        ios:
          app_id: 1:570942649027:ios:83855e7d7296731c97a876
          groups:
            - ios_testers
